In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
%matplotlib inline

In [9]:
df1 = pd.read_excel("C:/Users/Sushma Shekar/data-analysis-project/data/raw/online_retail_II.xlsx",sheet_name="Year 2009-2010")
df2 = pd.read_excel("C:/Users/Sushma Shekar/data-analysis-project/data/raw/online_retail_II.xlsx",sheet_name="Year 2010-2011")
df = pd.concat([df1,df2],ignore_index=True)
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [10]:
print(df.head())

  Invoice StockCode                          Description  Quantity  \
0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12
1  489434    79323P                   PINK CHERRY LIGHTS        12
2  489434    79323W                  WHITE CHERRY LIGHTS        12
3  489434     22041         RECORD FRAME 7" SINGLE SIZE         48
4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24

          InvoiceDate  Price  Customer ID         Country
0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom
1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom
3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom
4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom

In [11]:
df.shape

(1067371, 8)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[ns]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 65.1+ MB

In [13]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [14]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,1.067371e+06,1067371,1.067371e+06,824364.000000
mean,9.938898e+00,2011-01-02 21:13:55.394028544,4.649388e+00,15324.638504
min,-8.099500e+04,2009-12-01 07:45:00,-5.359436e+04,12346.000000
25%,1.000000e+00,2010-07-09 09:46:00,1.250000e+00,13975.000000
50%,3.000000e+00,2010-12-07 15:28:00,2.100000e+00,15255.000000
75%,1.000000e+01,2011-07-22 10:23:00,4.150000e+00,16797.000000
max,8.099500e+04,2011-12-09 12:50:00,3.897000e+04,18287.000000
std,1.727058e+02,NaN,1.235531e+02,1697.464450

In [15]:
df.describe(include='object')

        Invoice StockCode                         Description         Country
count   1067371   1067371                             1062989         1067371
unique    53628      5305                                5698              43
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq       1350      5829                                5918          981330

In [16]:
df.duplicated().sum()

np.int64(34335)

In [17]:
for col in df.columns:
    print(f"\n{col}")
    print(df[col].nunique())

Invoice
53628

StockCode
5305

Description
5698

Quantity
1057

InvoiceDate
47635

Price
2807

Customer ID
5942

Country
43

In [18]:
numerical_cols = df.select_dtypes(include=np.number).columns
df[numerical_cols].describe()

           Quantity         Price    Customer ID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [19]:
categorical_cols = df.select_dtypes(include='object').columns
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].value_counts())

Invoice
Invoice
537434     1350
538071     1304
537638     1202
537237     1194
536876     1186
           ...
C518262       1
548515        1
C548513       1
C524395       1
559376        1
Name: count, Length: 53628, dtype: int64

StockCode
StockCode
85123A       5829
22423        4424
85099B       4216
21212        3318
20725        3259
             ...
DCGS0067        1
DCGS0066P       1
DCGS0071        1
DCGS0073        1
90197A          1
Name: count, Length: 5305, dtype: int64

Description
Description
WHITE HANGING HEART T-LIGHT HOLDER     5918
REGENCY CAKESTAND 3 TIER               4412
JUMBO BAG RED RETROSPOT                3469
ASSORTED COLOUR BIRD ORNAMENT          2958
PARTY BUNTING                          2765
                                       ...
IVORY PENDANT SHELL NECKLACE              1
allocate stock for dotcom orders ta       1
PAINTED HEART WREATH WITH BELL            1
FLOWER FAIRY MUG+COASTER,ROSE             1
Zebra invcing error                       1
Name: count, Length: 5698, dtype: int64

Country
Country
United Kingdom          981330
EIRE                     17866
Germany                  17624
France                   14330
Netherlands               5140
Spain                     3811
Switzerland               3189
Belgium                   3123
Portugal                  2620
Australia                 1913
Channel Islands           1664
Italy                     1534
Norway                    1455
Sweden                    1364
Cyprus                    1176
Finland                   1049
Austria                    938
Denmark                    817
Unspecified                756
Greece                     663
Japan                      582
Poland                     535
USA                        535
United Arab Emirates       500
Israel                     371
Hong Kong                  364
Singapore                  346
Malta                      299
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        169
Bahrain                    126
Brazil                      94
Thailand                    76
Korea                       63
European Community          61
Lebanon                     58
West Indies                 54
Bermuda                     34
Nigeria                     32
Czech Republic              30
Saudi Arabia                10
Name: count, dtype: int64

In [20]:
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3-Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]
    print(f"{col} : {len(outliers)} outliers")

Quantity : 116489 outliers
Price : 68105 outliers
Customer ID : 0 outliers

In [21]:
df[numerical_cols].corr()

             Quantity     Price  Customer ID
Quantity     1.000000 -0.001319    -0.005430
Price       -0.001319  1.000000    -0.003835
Customer ID -0.005430 -0.003835     1.000000

In [22]:
pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (2.3.3)
Collecting matplotlib<=3.10,>=3.5 (from ydata-profiling)
  Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pydantic<3,>=2 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (2.3.5)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-win_amd64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (0.14.5)
Collecting typeguard<5,>=4 (from ydata-profiling)
  Downloading typeguard-4.5.2-py3-none-any.whl.metadata (3.8 kB)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting wordcloud>=1.9.4 (from ydata-profiling)
  Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl.metadata (3.5 kB)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\sushma shekar\anaconda3\lib\site-packages (from ydata-profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\sushma shekar\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\sushma shekar\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata-profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sushma shekar\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata-profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\sushma shekar\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\sushma shekar\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\sushma shekar\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\sushma shekar\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2.7.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sushma shekar\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in c:\users\sushma shekar\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\sushma shekar\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata-profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\sushma shekar\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\sushma shekar\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\sushma shekar\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading matplotlib-3.10.0-cp313-cp313-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.0 MB 4.3 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/8.0 MB 3.1 MB/s eta 0:00:03
   ------- -------------------------------- 1.6/8.0 MB 2.6 MB/s eta 0:00:03
   --------- ------------------------------ 1.8/8.0 MB 2.3 MB/s eta 0:00:03
   ----------- ---------------------------- 2.4/8.0 MB 2.1 MB/s eta 0:00:03
   ------------- -------------------------- 2.6/8.0 MB 2.0 MB/s eta 0:00:03
   -------------- ------------------------- 2.9/8.0 MB 2.0 MB/s eta 0:00:03
   ---------------- ----------------------- 3.4/8.0 MB 1.9 MB/s eta 0:00:03
   ------------------- -------------------- 3.9/8.0 MB 2.0 MB/s eta 0:00:03
   ----------------------- ---------------- 4.7/8.0 MB 2.2 MB/s eta 0:00:02
   ------------------------------------- -- 7.6/8.0 MB 3.2 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 3.3 MB/s  0:00:02
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-win_amd64.whl (678 kB)
   ---------------------------------------- 0.0/678.1 kB ? eta -:--:--
   ---------------------------------------- 678.1/678.1 kB 9.5 MB/s  0:00:00
Downloading typeguard-4.5.2-py3-none-any.whl (36 kB)
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ------------------------------------- -- 2.9/3.1 MB 16.0 MB/s eta 0:00:01
   ---------------------------------------- 3.1/3.1 MB 14.2 MB/s  0:00:00
Downloading wordcloud-1.9.6-cp313-cp313-win_amd64.whl (306 kB)
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
Installing collected packages: minify-html, filetype, typeguard, puremagic, multimethod, dacite, matplotlib, imagehash, wordcloud, visions, phik, ydata-profiling

   --- ------------------------------------  1/12 [filetype]
   ---------- -----------------------------  3/12 [puremagic]
   ---------------- -----------------------  5/12 [dacite]
  Attempting uninstall: matplotlib
   ---------------- -----------------------  5/12 [dacite]
    Found existing installation: matplotlib 3.10.6
   ---------------- -----------------------  5/12 [dacite]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
    Uninstalling matplotlib-3.10.6:
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
      Successfully uninstalled matplotlib-3.10.6
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   -------------------- -------------------  6/12 [matplotlib]
   ----------------------- ----------------  7/12 [imagehash]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   ------------------------------ ---------  9/12 [visions]
   --------------------------------- ------ 10/12 [phik]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ------------------------------------ --- 11/12 [ydata-profiling]
   ---------------------------------------- 12/12 [ydata-profiling]

Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 matplotlib-3.10.0 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 typeguard-4.5.2 visions-0.8.1 wordcloud-1.9.6 ydata-profiling-4.18.4
Note: you may need to restart the kernel to use updated packages.

In [23]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df,title="Data Profiling Report")
profile.to_file("data_profiling_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/8 [00:00<?, ?it/s]
 38%|███▊      | 3/8 [00:02<00:03,  1.54it/s]
 50%|█████     | 4/8 [00:02<00:02,  1.46it/s]
100%|██████████| 8/8 [00:02<00:00,  2.83it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]